### ISSUE TITLE
Serve /status and /recipes and /bags APIs under /-/tiddlywiki/ path prefix

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-tiddlywiki#6]
_Original title: Can /status and other API endpoints be /-/tiddlywiki/status instead?_

Datasette likes to reserve the top level namespace for serving databases - so it would be better to move the TiddlyWiki APIs under the `/-/tiddlywiki/...` path. Not sure how to do this though, would I have to modify the tiddlyweb plugin?

**Comment by simonw** [comment]
https://github.com/simonw/datasette-tiddlywiki/blob/7547485a5feb9ae0b8b6d57fb6577f771485b5b1/datasette_tiddlywiki/__init__.py#L138-L147

**Comment by simonw** [comment]
This code looks relevant: https://github.com/Jermolene/TiddlyWiki5/blob/master/plugins/tiddlywiki/tiddlyweb/tiddlywebadaptor.js

**Comment by simonw** [comment]
Jeremy linked me to: https://tiddlywiki.com/#Using%20a%20custom%20path%20prefix%20with%20the%20client-server%20edition

> By default, when running [TiddlyWiki on Node.js](https://tiddlywiki.com/#TiddlyWiki%20on%20Node.js), the server exposes the wiki at the URI formed from the protocol, host and port - for example, `http://127.0.0.1:8080/`.
> 
> There are two steps to running the wiki at a custom path like `http://127.0.0.1:8080/path/to/my/wiki/`:
> 
> 1.  Configure the server by passing `/path/to/my/wiki` as the **pathprefix** argument of the [ServerCommand](https://tiddlywiki.com/#ServerCommand)
> 2.  Configure the client by creating a tiddler called `$:/config/tiddlyweb/host` that contains `$protocol$//$host$/path/to/my/wiki/`

**Comment by simonw** [comment]
So maybe I inject a tiddler with `$:/config/tiddlyweb/host` that points to the alternative path. That way I could even support Datasette's `base_url` concept.

**Comment by simonw** [comment]
I tried injecting that tiddler and got some strange server logs:

```
INFO:     127.0.0.1:65227 - "OPTIONS /-/tiddlywiki HTTP/1.1" 200 OK
INFO:     127.0.0.1:65225 - "PUT /-/tiddlywikirecipes/undefined/tiddlers/%24%3A/StoryList HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:65225 - "GET /-/tiddlywiki/recipes/all/tiddlers.json?filter=%5Ball%5Btiddlers%5D%5D%20-%5B%5B%24%3A%2FisEncrypted%5D%5D%20-%5Bprefix%5B%24%3A%2Ftemp%2F%5D%5D%20-%5Bprefix%5B%24%3A%2Fstatus%2F%5D%5D%20-%5B%5B%24%3A%2Fboot%2Fboot.js%5D%5D%20-%5B%5B%24%3A%2Fboot%2Fbootprefix.js%5D%5D%20-%5B%5B%24%3A%2Flibrary%2Fsjcl.js%5D%5D%20-%5B%5B%24%3A%2Fcore%5D%5D HTTP/1.1" 200 OK
INFO:     127.0.0.1:65228 - "PUT /-/tiddlywiki/recipes/all/tiddlers/%24%3A/StoryList HTTP/1.1" 204 No Content
INFO:     127.0.0.1:65228 - "GET /-/tiddlywiki/recipes/all/tiddlers/New%20Tiddler HTTP/1.1" 200 OK
INFO:     127.0.0.1:65228 - "GET /-/tiddlywiki/recipes/all/tiddlers/%24%3A/DefaultTiddlers HTTP/1.1" 200 OK
INFO:     127.0.0.1:65228 - "GET /-/tiddlywiki/recipes/all/tiddlers/I%20only%20want%20to%20see%20this HTTP/1.1" 200 OK
INFO:     127.0.0.1:65228 - "GET /-/tiddlywiki/recipes/all/tiddlers/%24%3A/StoryList HTTP/1.1" 200 OK
INFO:     127.0.0.1:65228 - "GET /-/tiddlywikirecipes/undefined/tiddlers.json?filter=%5Ball%5Btiddlers%5D%5D%20-%5B%5B%24%3A%2FisEncrypted%5D%5D%20-%5Bprefix%5B%24%3A%2Ftemp%2F%5D%5D%20-%5Bprefix%5B%24%3A%2Fstatus%2F%5D%5D%20-%5B%5B%24%3A%2Fboot%2Fboot.js%5D%5D%20-%5B%5B%24%3A%2Fboot%2Fbootprefix.js%5D%5D%20-%5B%5B%24%3A%2Flibrary%2Fsjcl.js%5D%5D%20-%5B%5B%24%3A%2Fcore%5D%5D HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:65228 - "PUT /-/tiddlywikirecipes/undefined/tiddlers/%24%3A/StoryList HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:65234 - "PUT /-/tiddlywikirecipes/undefined/tiddlers/%24%3A/StoryList HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:65238 - "PUT /-/tiddlywikirecipes/undefined/tiddlers/%24%3A/StoryList HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:65240 - "PUT /-/tiddlywikirecipes/undefined/tiddlers/%24%3A/StoryList HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:65241 - "PUT /-/tiddlywikirecipes/undefined/tiddlers/%24%3A/StoryList HTTP/1.1" 404 Not Found
```
It starts out correctly, hitting `/-/tiddlywiki/recipes/all/tiddlers/`

But then for some reason it starts making more requests to `/-/tiddlywikirecipes/undefined/tiddlers/%24%3A/StoryList`

**Comment by simonw** [comment]
That was injecting this Tiddler:
```json
{
    "title": "$:/config/tiddlyweb/host",
    "text": "http://127.0.0.1:3411/-/tiddlywiki/"
}
```

**Comment by Jermolene** [comment]
> That was injecting this Tiddler:
> 
> ```json
> {
>     "title": "$:/config/tiddlyweb/host",
>     "text": "http://127.0.0.1:3411/-/tiddlywiki/"
> }
> ```

Try setting the text to `$protocol$//$host$/-/tiddlywiki/` – in other words, the `$` delimited tokens are subsituted by the system.

**Comment by simonw** [comment]
> Try setting the text to `$protocol$//$host$/-/tiddlywiki/` – in other words, the `$` delimited tokens are subsituted by the system.

Yes! That worked perfectly, thank you.
